name: AnyWars
version: '${version}'
main: org.super89.supermegamod.testnewfeautres.TestNewFeautres
api-version: '1.20'
website: https://discord.gg/gWcX5kAHhH
authors:
  - Super89
depend:
  - Citizens
commands:
  game:
    description: начать игру
    usage: Что-то сломалось)
  anywars:
    aliases:
      - aw
    description: Основная команда.
    usage: /<command> create name max-size team-count min-count

